imixs-adapters-datev/src/main/java/org/imixs/workflow/datev/controller/DatevBookingController.java
/*******************************************************************************
 *  Imixs Workflow Technology
 *  Copyright (C) 2003, 2008 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika
 *  
 *******************************************************************************/
package org.imixs.workflow.datev.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

import org.imixs.workflow.ItemCollection;
import org.imixs.workflow.datev.DatevService;
import org.imixs.workflow.exceptions.AccessDeniedException;
import org.imixs.workflow.faces.data.WorkflowController;
import org.imixs.workflow.faces.data.WorkflowEvent;

import jakarta.enterprise.context.ConversationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;
import jakarta.inject.Named;

/**
 * Der DatevBookingController verwaltet die Buchungszeilen in einer Form
 * 
 * @author rsoika
 * @version 1.0
 */
@Named
@ConversationScoped
public class DatevBookingController implements Serializable {

    private static final long serialVersionUID = 1L;
    private static Logger logger = Logger.getLogger(DatevBookingController.class.getName());

    protected List<ItemCollection> bookingList = null;

    @Inject
    WorkflowController workflowController;

    @Inject
    DatevService datevService;

    private List<DatevSearchEntry> searchResult = null;

    public void setBookingList(List<ItemCollection> bookingList) {
        this.bookingList = bookingList;
    }

    /**
     * This method returns a ItemCollections for each booking row stored in the
     * property datev.booking.list.
     * 
     * Example: <code>
     *   #{datevchildController.childItems}
     * </code>
     * 
     * @return
     */
    public List<ItemCollection> getBookingList() {
        return bookingList;
    }

    /**
     * Adds a new order item
     */
    public void add() {
        if (bookingList != null) {
            ItemCollection itemCol = new ItemCollection();
            itemCol.replaceItemValue("numPos", bookingList.size() + 1);
            bookingList.add(itemCol);
        }
    }

    public void remove(int pos) {
        if (bookingList != null) {
            bookingList.remove(pos - 1);
        }

        // now we need to reorder the numPos attribute for all existing childs..
        int iPos = 1;
        for (ItemCollection item : bookingList) {
            item.replaceItemValue("numPos", iPos);
            iPos++;
        }

    }

    /**
     * WorkflowEvent listener to convert embeded HashMaps into ItemCollections and
     * reconvert them before processing
     * 
     * @param workflowEvent
     * @throws AccessDeniedException
     */
    public void onWorkflowEvent(@Observes WorkflowEvent workflowEvent) throws AccessDeniedException {

        int eventType = workflowEvent.getEventType();
        ItemCollection workitem = workflowEvent.getWorkitem();
        if (workitem == null) {
            return;
        }

        // reset orderItems if workItem has changed
        if (WorkflowEvent.WORKITEM_CHANGED == eventType || WorkflowEvent.WORKITEM_CREATED == eventType) {
            // reset state
            bookingList = explodeChildList(workitem, DatevService.ITEM_DATEV_BOOKING_LIST);
        }

        // before the workitem is saved we update the field txtOrderItems
        if (WorkflowEvent.WORKITEM_BEFORE_PROCESS == eventType) {
            implodeChildList(workitem, bookingList, DatevService.ITEM_DATEV_BOOKING_LIST);
        }

        if (WorkflowEvent.WORKITEM_AFTER_PROCESS == eventType) {
            // reset state
            bookingList = explodeChildList(workitem, DatevService.ITEM_DATEV_BOOKING_LIST);
        }

    }

    /**
     * converts the Map List of a workitem into a List of ItemCollectons
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public static List<ItemCollection> explodeChildList(ItemCollection workitem, String childItemName) {
        // convert current list of childItems into ItemCollection elements
        ArrayList<ItemCollection> result = new ArrayList<ItemCollection>();

        List<Object> mapOrderItems = workitem.getItemValue(childItemName);
        for (Object mapOderItem : mapOrderItems) {
            if (mapOderItem instanceof Map) {
                ItemCollection itemCol = new ItemCollection((Map) mapOderItem);
                result.add(itemCol);
            }
        }
        return result;
    }

    /**
     * Convert the List of ItemCollections back into a List of Map elements
     * 
     * @param workitem
     */
    @SuppressWarnings({ "rawtypes" })
    public static void implodeChildList(ItemCollection workitem, List<ItemCollection> _childItems,
            String childItemName) {
        List<Map> mapOrderItems = new ArrayList<Map>();
        // convert the child ItemCollection elements into a List of Map
        if (_childItems != null) {
            // iterate over all order items..
            for (ItemCollection orderItem : _childItems) {
                mapOrderItems.add(orderItem.getAllItems());
            }
            workitem.replaceItemValue(childItemName, mapOrderItems);
        }
    }

}

imixs-adapters-datev/src/main/java/org/imixs/workflow/datev/controller/DatevController.java
package org.imixs.workflow.datev.controller;

import java.io.ByteArrayInputStream;

/*******************************************************************************
 *  Imixs Workflow Technology
 *  Copyright (C) 2003, 2008 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika
 *  
 *******************************************************************************/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import org.imixs.workflow.FileData;
import org.imixs.workflow.ItemCollection;
import org.imixs.workflow.datev.DatevException;
import org.imixs.workflow.datev.DatevService;
import org.imixs.workflow.datev.imports.DatevImportService;
import org.imixs.workflow.engine.DocumentService;
import org.imixs.workflow.engine.index.UpdateService;
import org.imixs.workflow.engine.scheduler.Scheduler;
import org.imixs.workflow.exceptions.AccessDeniedException;
import org.imixs.workflow.exceptions.PluginException;
import org.imixs.workflow.faces.data.WorkflowController;
import org.imixs.workflow.faces.fileupload.FileUploadController;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.SessionScoped;
import jakarta.faces.model.SelectItem;
import jakarta.inject.Inject;
import jakarta.inject.Named;

/**
 * The DatevController is used to configure the DatevScheduler. This service is
 * used to generate datev export workitems.
 * <p>
 * The Controller creates a configuration entity:
 * type=configuration name=datev
 * <p>
 * 
 * @author rsoika
 * 
 */
@Named
@SessionScoped
public class DatevController implements Serializable {

	private ItemCollection importData;

	private ItemCollection configuration = null;

	private static final long serialVersionUID = 1L;
	private static Logger logger = Logger.getLogger(DatevController.class.getName());

	@Inject
	DocumentService documentService;

	@Inject
	UpdateService updateService;

	@Inject
	DatevService datevService;

	@Inject
	DatevImportService datevImportService;

	@Inject
	WorkflowController workflowController;

	@Inject
	protected FileUploadController fileUploadController;

	/**
	 * This method load the config entity after postContstruct. If no Entity exists
	 * than the ConfigService EJB creates a new config entity.
	 * 
	 */
	@PostConstruct
	public void init() {
		configuration = loadConfiguration();
	}

	public String getName() {
		return DatevService.DATEV_CONFIGURATION;
	}

	public ItemCollection getConfiguration() {
		if (configuration == null) {
			configuration = new ItemCollection();
			configuration.setItemValue("$workflowsummary", getName());
			configuration.setItemValue(Scheduler.ITEM_SCHEDULER_NAME, getName());
		}
		return configuration;
	}

	public void setConfiguration(ItemCollection configuration) {
		this.configuration = configuration;
	}

	/**
	 * Loads the scheduler configuration entity by name. The method returns null if
	 * no scheduler configuration exits.
	 * 
	 * @return
	 */
	public ItemCollection loadConfiguration() {

		configuration = datevService.loadConfiguration();

		return configuration;
	}

	/**
	 * This method saves the DATEV configuration. The method ensures that the
	 * following properties are set to default.
	 * <ul>
	 * <li>type</li>
	 * <li>name</li>
	 * <li>$writeAccess</li>
	 * <li>$readAccess</li>
	 * </ul>
	 * The method also updates the timer details of a running timer.
	 * 
	 * @return
	 * @throws AccessDeniedException
	 */
	public ItemCollection saveConfiguration() {
		configuration = datevService.saveConfiguration(configuration);
		return configuration;
	}

	/**
	 * Diese Methode liefert eine liste von SelectItem Elementen mit den Werten des
	 * Buchungsschlüssels zurück.
	 * <p>
	 * Der Buchungschlüssel wird in folgendem Format im config entity
	 * DATEV_CONFIGURATION gespeichert
	 * 
	 * {@code
	 *  BEZEICHNUNG | DATEV_BU_SCHLUESSEL | PROZENTSATZ
	 *  }
	 * 
	 * <p>
	 * 
	 * @return
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public List<SelectItem> getBuSchluesel() throws Exception {

		ArrayList<SelectItem> selection;
		selection = new ArrayList<SelectItem>();

		// check if a value for this param is available...
		// if not return an empty list
		if (!this.configuration.hasItem("datev.buschluessel")) {
			return selection;
		}

		// get value list first value from vector if size >0
		List<String> valueList = this.configuration.getItemValue("datev.buschluessel");
		for (String aValue : valueList) {

			String[] parts = aValue.split("\\|");

			if (parts == null || parts.length < 3) {
				logger.warning(
						"Falsche Konfiguration der _buschluessel - Format: BEZEICHNUNG | DATEV_BU_SCHLUESSEL | PROZENTSATZ");
				continue;
			}
			// Es wird hier der DATEV BU Schlüssel ausgegeben. Das MandantPlugin errechnet
			// später den Prozentzsatz.
			selection.add(new SelectItem(parts[1].trim(), parts[0].trim()));

		}
		return selection;
	}

	/**
	 * Returns costcentre1 from the Corporate Space as an ArrayList of SelectItems
	 * objects. A param entry can be devided by a | into a label and a value
	 * component. Example:
	 * 
	 * <code>
	 *   17431 | Blaue Stadt I
		 17435 | Blaue Stadt I
		 17400 | Overhead/General
	 * </code>
	 * 
	 * <code>
	 * <f:selectItems value="#{datevController.costcentre2}" />
	 * </code>
	 * 
	 * @return
	 * @throws Exception
	 */
	public List<SelectItem> getKostenstelle1() throws Exception {

		ArrayList<SelectItem> selection;
		selection = new ArrayList<SelectItem>();

		// check if we have a workitem and space
		if (workflowController.getWorkitem() == null) {
			return selection;
		}

		// get value list first value from vector if size >0
		List<?> valueList = configuration.getItemValue("datev.kostenstelle1");
		for (Object aValue : valueList) {
			// test if aValue has a | as an delimiter
			String sValue = aValue.toString();
			if (sValue.trim().isEmpty()) {
				continue;
			}
			String sName = sValue;

			if (sValue.indexOf("|") > -1) {
				sValue = sValue.substring(0, sValue.indexOf("|"));
				sName = sName.substring(sName.indexOf("|") + 1);
			}
			selection.add(new SelectItem(sValue.trim(), sName.trim()));

		}

		return selection;
	}

	/**
	 * Gibt die Bezeichnung der Kostenstelle mit nummer - so wie bei suche
	 * 
	 * @param value
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public String getKostenstelle1Read(String value) {

		// get value list first value from vector if size >0
		List<String> valueList = configuration.getItemValue("datev.kostenstelle1");

		for (String aValue : valueList) {
			String[] parts = aValue.split("\\|");
			if (parts == null || parts.length < 1) {
				return value;
			}
			String nummer = parts[0];
			String bez = nummer;
			if (parts.length > 1) {
				bez = parts[1];
			}

			if (value.equals(nummer)) {
				if (bez.startsWith(nummer)) {
					return bez;
				} else {
					return nummer + " " + bez;
				}
			}
		}

		return value;
	}

	/**
	 * Returns costcentre2 from the Object Space as an ArrayList of SelectItems
	 * objects. A param entry can be devided by a | into a label and a value
	 * component. Example:
	 * 
	 * <code>
	 *   17431 | Blaue Stadt I
	     17435 | Blaue Stadt I
	     17400 | Overhead/General
	 * </code>
	 * 
	 * <code>
	 * <f:selectItems value="#{datevController.costcentre2}" />
	 * </code>
	 * 
	 * @return
	 * @throws Exception
	 */
	public List<SelectItem> getKostenstelle2() throws Exception {

		ArrayList<SelectItem> selection;
		selection = new ArrayList<SelectItem>();

		// check if we have a workitem and space
		if (workflowController.getWorkitem() == null) {
			return selection;
		}

		// get value list first value from vector if size >0
		List<?> valueList = configuration.getItemValue("datev.kostenstelle2");
		for (Object aValue : valueList) {
			// test if aValue has a | as an delimiter
			String sValue = aValue.toString();
			if (sValue.trim().isEmpty()) {
				continue;
			}
			String sName = sValue;

			if (sValue.indexOf("|") > -1) {
				sValue = sValue.substring(0, sValue.indexOf("|"));
				sName = sName.substring(sName.indexOf("|") + 1);
			}
			selection.add(new SelectItem(sValue.trim(), sName.trim()));

		}

		return selection;
	}

	/**
	 * Gibt die Bezeichnung der Kostenstelle mit nummer - so wie bei suche
	 * 
	 * @param value
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public String getKostenstelle2Read(String value) {

		// get value list first value from vector if size >0
		List<String> valueList = configuration.getItemValue("datev.kostenstelle2");

		for (String aValue : valueList) {
			String[] parts = aValue.split("\\|");
			if (parts == null || parts.length < 1) {
				return value;
			}
			String nummer = parts[0];
			String bez = nummer;
			if (parts.length > 1) {
				bez = parts[1];
			}

			if (value.equals(nummer)) {
				if (bez.startsWith(nummer)) {
					return bez;
				} else {
					return nummer + " " + bez;
				}
			}
		}

		return value;
	}

	/**
	 * Itemcollection containing file import
	 * data
	 * 
	 * @return
	 */
	public ItemCollection getImportData() {
		if (importData == null) {
			importData = new ItemCollection();
		}
		return importData;
	}

	public void setImportData(ItemCollection importData) {
		this.importData = importData;
	}

	/**

imixs-adapters-datev/src/main/webapp/forms/datev/booking_account.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions">

	<h:panelGroup layout="block" styleClass="imixs-form-section" style="position: relative;"
		id="bookinglist" binding="#{bookinglistContainer}">	
	

		<ui:param name="hasKostenstelle1" value="#{!empty datevController.kostenstelle1}"></ui:param>
		<ui:param name="hasKostenstelle2" value="#{!empty datevController.kostenstelle2}"></ui:param>

		<ui:fragment rendered="#{!readonly}">
			<h:commandScript name="sachkontoSearch" action="#{datevSearchController.searchSachkonto()}"
				render="autocomplete-resultlist-datev-sachkonto" onevent="autocompleteShowResult" />
			<table class="imixsdatatable imixs-bookingitems"> 
				<tr>
					<th style="width: 200px;">Buchungskonto</th>
					<!-- -->
					<ui:fragment rendered="#{hasKostenstelle1}">
						<th style="width: 140px;">Kostenstelle I.</th>
					</ui:fragment>
					<ui:fragment rendered="#{hasKostenstelle2}">
						<th style="width: 140px;">Kostenstelle  II.</th>
					</ui:fragment>
					<th style="width: 170px;">BU Schlüssel</th>
					<th style="min-width: 120px;">Betrag</th>
					<th style="width: 10px;">
						<!-- delete -->
					</th>
				</tr>
				<ui:repeat var="bookingItem"
					value="#{datevBookingController.bookingList}">
					<tr>
						<td class="konto-input">
							<!-- Input Field -->						
							<h:panelGroup id="konto_input_box"
								layout="block" class="marty-userinput-inputbox"
								style="height:inherit;">
								<h:inputText style="width:100%;" id="konto-input-id" 
								value="#{bookingItem.item['datev.konto']}" pt:data-item="datev.sachkonto"  />
								<h:inputHidden value="#{bookingItem.item['datev.kontobeschriftung']}" pt:data-item="datev.kontobeschriftung" />
								<br />
								<span id='sachkontodtr-name-id' class='small'>#{bookingItem.item['datev.kontobeschriftung']}</span>
							</h:panelGroup>

						</td>

						<!-- Kostenstelle -->
						<ui:fragment rendered="#{!empty datevController.kostenstelle1}">
							<td><h:selectOneMenu style="width:100%;"
									value="#{bookingItem.item['datev.kostenstelle1']}">
									<f:selectItem itemLabel="" itemValue="" />
									<f:selectItems value="#{datevController.kostenstelle1}"></f:selectItems>
								</h:selectOneMenu></td>
						</ui:fragment>
						<ui:fragment rendered="#{!empty datevController.kostenstelle2}">
							<td><h:selectOneMenu style="width:100%;"
									value="#{bookingItem.item['datev.kostenstelle2']}">
									<f:selectItem itemLabel="" itemValue="" />
									<f:selectItems value="#{datevController.kostenstelle2}"></f:selectItems>
								</h:selectOneMenu></td>
						</ui:fragment>


						<td><h:selectOneMenu  style="width:100%;" 
								value="#{bookingItem.item['datev.buschluessel']}">
								<f:selectItems
									value="#{datevController.buSchluesel}"></f:selectItems>
								<f:selectItem itemLabel="" itemValue=""></f:selectItem>
							</h:selectOneMenu></td>

						<td style="text-align: right;"><h:inputText
								value="#{bookingItem.item['datev.betrag']}" id="bookingitem_amount"
								style="text-align: right;width: 100%;border: inherit;"
								onchange="calculateSummary()">
								<f:convertNumber minFractionDigits="2" locale="de" />
							</h:inputText></td>

						<td><h:commandLink
								actionListener="#{datevBookingController.remove(bookingItem.item['numpos'])}">
								<span class="typcn typcn-trash imixs-state-info"></span>
								<f:ajax render="#{bookinglistContainer.clientId}"  execute="#{bookinglistContainer.clientId}" 
									onevent="initDatevTable" />
							</h:commandLink></td>

					</tr>

				</ui:repeat>

				<!-- summary -->
				<tr>
					<td />
					<ui:fragment rendered="#{hasKostenstelle1}">
						<td />
					</ui:fragment>
					<ui:fragment rendered="#{hasKostenstelle2}">
						<td />
					</ui:fragment>
					
					<td class="bookinglist-sum"
						style="text-align: right; font-weight: bold;">Summe:</td>
					<td class="bookinglist-sum bookinglist_summary"
						style="text-align: right; font-weight: bold;"></td>
					<td />
				</tr>
			</table>

			<!-- total summary -->
			<h:inputHidden value="#{workitem.item['_capacity']}"
				id="bookingitems_capacity" />
			<h:inputHidden value="#{workitem.item['_capacity_dsp']}"
				id="bookingitems_capacity_dsp" />

			<h:commandButton value="#{message.add}" id="addposbutton_id"
				actionListener="#{datevBookingController.add}">
				<f:ajax render="#{bookinglistContainer.clientId}"  execute="#{bookinglistContainer.clientId}" 
					onevent="initDatevTable" />
			</h:commandButton>

			<!-- datev creditor suggest list -->
			<h:panelGroup id="autocomplete-resultlist-datev-sachkonto" layout="block" class="autocomplete-resultlist autocomplete-resultlist-sachkonto">
				<ui:repeat var="suggest" value="#{datevSearchController.searchResult}">
					<div class="autocomplete-resultlist-element" onclick="autocompleteSelectElement('#{suggest.data}')">
						<a href="#" style="color: #777;">
							<h:outputText value="#{suggest.display}" escape="false" />
						</a>
					</div>
				</ui:repeat>
			</h:panelGroup>
	

			<script type="text/javascript">
				/*<![CDATA[*/

				// display summary
				$(document).ready(
					function() {		
						calculateSummary();
						initDatevTable();
				});
				
				// Hier bekommen wir die JSON Struktur mit allen Daten.
				// diese Daten werden auf die einzelnen Felder verteilt.
				function selectSachkontoCallback(selection,inputElementKonto) {
					const sachkontoData = JSON.parse(selection);
					inputElementKonto.val(sachkontoData.konto);
					// finde das nächste hidden Feld...
					var inputElementBeschriftung=$(inputElementKonto).siblings( "input" );
					inputElementBeschriftung.val(sachkontoData.name);
					// remove old cdtr.name
					$(inputElementKonto).siblings( "span" ).remove();
					// append span with cdtr.name....
					inputElementKonto.after("<span id='sachkonto-name-id' class='small'>" + sachkontoData.name + "</span>");
				}
			

				/* initialisiert die suchfunktion in der Tabelle */
				function initDatevTable(data) {
					if (!data || data.status === 'success') {
						// add autocomplete feature ..
						var sachkontoInput = $("input[data-item='datev.sachkonto']");
						$(sachkontoInput).each(function () {
							$(this).addClass("imixs-ml");
							autocompleteInitInput(this, sachkontoSearch, 'autocomplete-resultlist-datev-sachkonto', selectSachkontoCallback);
						});
						$('[id$=bookinglist]').imixsLayout();
					}
				} 


				//Rechnet die Preise zusammen
				function calculateSummary() {
					var price = 0, amount = 0, sum = 0, total = 0;
					var summaryItems = $("[id$=bookingitem_amount]");
					$(summaryItems).each(function(index, value) {

						var amount = convertToNumber($(this).val());
						if (!isNaN(amount)) {
							amount = amount * 1; // convert to number
							total = total + amount;
							total = Math.round(total * 100) / 100;
						}
					});

					// update total _capacity
					// update bookinglist_summary
					$("[id$=bookingitems_capacity]").val(total);
					$("[id$=bookingitems_capacity_dsp]").val(convertToCurrency(total));
					$(".bookinglist_summary", ".imixs-bookingitems").empty();
					$(".bookinglist_summary", ".imixs-bookingitems").append(
							convertToCurrency(total));

				}

				/* format 1.000,00 to 1000.00 */
				function convertToNumber(currency) {
					currency = currency.replace(/\./g, '');
					currency = currency.replace(/\,/g, '.');
					return currency;
				}
				/* format 1000 into 1.000,00 */ 
				function convertToCurrency(number) {
					var splitNum;
					//number = Math.abs(number);
					number = number.toFixed(2);
					splitNum = number.split('.');
					splitNum[0] = splitNum[0].replace(/\B(?=(\d{3})+(?!\d))/g, ".");
					return splitNum.join(",");
				}
						
				/*]]>*/
			</script>
		</ui:fragment>

		<ui:fragment rendered="#{readonly}">
			<table class="imixsdatatable imixs-bookingitems">
				<tr>
					<th style="width: 300px;">Buchungskonto</th>
					<!-- -->
					<ui:fragment rendered="#{hasKostenstelle1}">
						<th style="width: 140px;">Kostenstelle I.</th>
					</ui:fragment>
					<ui:fragment rendered="#{hasKostenstelle2}">
						<th style="width: 140px;">Kostenstelle  II.</th>
					</ui:fragment>
					<th style="width: 70px;">BU Schlüssel</th>
					<th style="width: 50px;">Betrag</th>
				</tr>

				<ui:repeat var="bookingItem"
					value="#{datevBookingController.bookingList}">
					<tr>
						<td class="konto-input"><h:outputText
								value="#{bookingItem.item['datev.konto']}"></h:outputText>
								<h:outputText
								value=" #{bookingItem.item['datev.kontobeschriftung']}"></h:outputText>
						</td>
 


						<!-- Kostenstelle -->
						<ui:fragment rendered="#{!empty datevController.kostenstelle1}">
							<td><h:outputText value="#{bookingItem.item['datev.kostenstelle1']}"></h:outputText></td>
						</ui:fragment>
						<ui:fragment rendered="#{!empty datevController.kostenstelle2}">
							<td><h:outputText value="#{bookingItem.item['datev.kostenstelle2']}"></h:outputText></td>
						</ui:fragment>
						<td style="text-align: right;">
							<h:outputText value="#{bookingItem.item['datev.buschluessel']}"></h:outputText>
						</td>

						<td style="text-align: right;"><h:outputText
								value="#{bookingItem.item['datev.betrag']}"></h:outputText></td>
					</tr>
				</ui:repeat>
				<!-- summary -->
				<tr>

					<td />
					<ui:fragment rendered="#{hasKostenstelle1}">
						<td />
					</ui:fragment>
					<ui:fragment rendered="#{hasKostenstelle2}">
						<td />
					</ui:fragment>
					<td class="bookinglist-sum"
						style="text-align: right; font-weight: bold;">Summe:</td>
					<td class="bookinglist-sum bookinglist_summary"
						style="text-align: right; font-weight: bold;">#{workitem.item['_capacity_dsp']}</td>
				</tr>
			</table>
		</ui:fragment>
	</h:panelGroup>

</ui:composition>